# Generated by Django 2.2 on 2020-03-19 10:12

from django.db import migrations, models
import django.db.models.deletion
import reservations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('phone', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('arrival', models.DateField(validators=[reservations.validators.validate_reservation_date_bigger_than_yesterday])),
                ('departure', models.DateField(validators=[reservations.validators.validate_reservation_date_bigger_than_yesterday])),
                ('no_of_people', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.ClientModel')),
            ],
        ),
    ]
